flowchart TB

    %% Actores externos
    P["Pasajero"]
    O["Operador"]
    G["Bus / GPS"]

    subgraph APP["RutaSIT Arequipa - Monolito modular "]

        API["Capa de presentacion / API<br/>Consultas y recepcion GPS"]

        U["Ubicaciones"]
        R["Rutas y buses"]
        E["Calculo de ETA"]
        A["Alertas"]
        C["Consultas"]

        INF["Capa de infraestructura:<br/>persistencia e integraciones externas"]

        API --> U
        API --> R
        API --> C

        U --> E
        R --> E

        U --> A
        R --> A

        E --> C
        A --> C

        U --> INF
        R --> INF
        E --> INF
        A --> INF
        C --> INF
    end

    DB[("Base de datos")]
    MAP["Servicio externo<br/>de mapas"]

    P --> API
    O --> API
    G --> API

    INF --> DB
    INF --> MAP

    %% Estilos
    classDef actor fill:#FDECEC,stroke:#D9534F,color:#000;
    classDef module fill:#EAF6EA,stroke:#5A9E5A,color:#000;
    classDef layer fill:#EEE8FF,stroke:#7667B8,color:#000;
    classDef external fill:#F7F7F7,stroke:#777,color:#000,stroke-dasharray:4 3;

    class P,O,G actor;
    class U,R,E,A,C module;
    class API,INF layer;
    class MAP external;